const {el,labeledValue,button,clear}=require('./components');
function electorateViewModel(model={}){const source=(model.cohorts||[]).slice().sort((a,b)=>(b.share||0)-(a.share||0));let percents=source.map(c=>Math.round((Number(c.share)||0)*100));const diff=100-percents.reduce((a,b)=>a+b,0);if(percents.length)percents[percents.length-1]+=diff;return{cohorts:source.map((c,i)=>({...c,percent:percents[i]})),confidence:Number.isFinite(model.confidence)?`${Math.round(model.confidence*100)}%`:'Unavailable',empty:source.length===0};}
function renderElectoratePanel(doc,target,model,options={}){const vm=electorateViewModel(model);target.append(el(doc,'h2','pm-section-title',options.title||'Electorate Ideology'));target.append(labeledValue(doc,'Model confidence',vm.confidence));if(vm.empty)target.append(el(doc,'p','pm-muted','Electorate ideology data unavailable.'));const grid=el(doc,'div','pm-grid');for(const c of vm.cohorts.slice(0,18)){const card=el(doc,'div','pm-card');card.append(labeledValue(doc,c.name||c.id,`${c.percent}%`),labeledValue(doc,'Family',c.family||'Unavailable'));grid.append(card);}target.append(grid);
  if(options.candidateFits?.length){target.append(el(doc,'h3','pm-subtitle','Candidate coalition fit'));for(const row of options.candidateFits.slice(0,12))target.append(labeledValue(doc,row.name,`${Math.round(row.fit*100)}%`));}
  return vm;}
function renderElectorateBrowser(doc,target,electorates,services={}){
  target.append(el(doc,'h2','pm-section-title','Electorates'));if(services.back)target.append(button(doc,'Back to Political Intelligence',services.back));
  const picker=el(doc,'select','pm-select'),host=el(doc,'div','pm-electorate-host');for(const e of electorates){const o=el(doc,'option',null,e.label||e.id);o.value=e.id;picker.append(o);}target.append(picker,host);
  function draw(){clear(host);const electorate=electorates.find(e=>String(e.id)===String(picker.value))||electorates[0];if(!electorate){host.append(el(doc,'p','pm-muted','No native electorate data is available in the current game state.'));return null;}const model=services.inferCohorts(electorate);const candidateFits=(services.records||[]).map(r=>({name:r.name,fit:services.analyzeCandidate({dimensions:r.ideology?.dimensions||{},party:r.party},r.politicalStyle,model).overallFit})).sort((a,b)=>b.fit-a.fit);renderElectoratePanel(doc,host,model,{title:electorate.label,candidateFits});return model;}
  picker.addEventListener('change',draw);return draw();
}
module.exports={electorateViewModel,renderElectoratePanel,renderElectorateBrowser};
