const test=require('node:test');const assert=require('node:assert/strict');const{scorePolitician,distance}=require('../../src/projectMaverick/ideology/scoring');const{DIMENSIONS}=require('../../src/projectMaverick/ideology/dimensions');
test('progressive policy evidence produces left/progressive dimensions',()=>{const r=scorePolitician({fiscalScore:-.7,socialScore:-.8,issues:{taxes:-.8,healthcare:-1,guns:-.7,immigration:-.8,environment:-.9,education:-.5}});assert.ok(r.dimensions.economics<0);assert.ok(r.dimensions.social<0);assert.ok(r.dimensions.healthcare<0);assert.ok(r.dimensions.environment<0);assert.ok(r.confidence>.5);});
test('libertarian evidence stays economically market-oriented and socially permissive',()=>{const r=scorePolitician({fiscalScore:.8,socialScore:-.7,issues:{taxes:.9,guns:.9,immigration:-.6,healthcare:.7}});assert.ok(r.dimensions.economics>0);assert.ok(r.dimensions.social<0);assert.ok(r.dimensions.guns>0);});
test('cross-pressured evidence is preserved instead of averaged away',()=>{const r=scorePolitician({fiscalScore:-.7,socialScore:.8,issues:{welfare:-.8,immigration:.8}});assert.ok(r.dimensions.economics<-.3);assert.ok(r.dimensions.social>.3);});
test('sparse data returns all dimensions but low confidence',()=>{const r=scorePolitician({fiscalScore:.2});assert.deepEqual(Object.keys(r.dimensions).sort(),[...DIMENSIONS].sort());assert.ok(r.confidence<.4);});
test('ideological distance is bounded and symmetric',()=>{const a=Object.fromEntries(DIMENSIONS.map(k=>[k,-1])),b=Object.fromEntries(DIMENSIONS.map(k=>[k,1]));assert.equal(distance(a,b),2);assert.equal(distance(a,b),distance(b,a));});
test('native ideology labels and v0.353 policy keys produce meaningful multidimensional scores',()=>{const r=scorePolitician({fiscalScore:'Liberal',socialScore:'Liberal',issues:{minWage:true,govAid:true,upperMain:'Increase',flatTax:false,gunControl:true,deadlyForce:false,commColl:true,schoolChoice:false,citPath:true,tightBorder:false,gayMarriage:true,illegalAbortion:false,proChoice:true,climatePol:true,oilLand:false,uniHealth:true,singlePay:true}});assert.ok(r.dimensions.economics<-.25);assert.ok(r.dimensions.fiscal<-.2);assert.ok(r.dimensions.welfare<-.2);assert.ok(r.dimensions.social<-.35);assert.ok(r.dimensions.immigration<-.2);assert.ok(r.dimensions.environment<-.2);assert.ok(r.dimensions.guns<-.2);assert.ok(r.dimensions.healthcare<-.2);assert.ok(r.dimensions.education<-.1);assert.ok(r.confidence>.55);});
test('Libertarian native fiscal/social labels preserve cross-dimensional ideology',()=>{const r=scorePolitician({fiscalScore:'Libertarian',socialScore:'Libertarian',issues:{}});assert.ok(r.dimensions.economics>.4);assert.ok(r.dimensions.fiscal>.4);assert.ok(r.dimensions.social<-.4);});
test('native policy rule lookup keys are normalized lowercase identifiers',()=>{const{POLICY_RULES}=require('../../src/projectMaverick/ideology/scoring');assert.ok(Object.keys(POLICY_RULES).every(key=>key===key.toLowerCase().replace(/[^a-z]/g,'')));assert.ok(POLICY_RULES.handgunban);assert.ok(POLICY_RULES.ccnopermit);});
