const { DIMENSIONS } = require('./dimensions');
function clamp(v) { return Math.max(-1, Math.min(1, Number.isFinite(v) ? v : 0)); }
const IDEOLOGY_LABELS=Object.freeze({ ultralib:-1, liberal:-.68, moderate:0, conservative:.68, ultracon:1 });
function norm(v, dimension) { if(typeof v==='string'){const key=v.toLowerCase().replace(/[^a-z]/g,'');if(key==='libertarian')return dimension==='social'?-.78:.82;if(IDEOLOGY_LABELS[key]!=null)return IDEOLOGY_LABELS[key];}v=Number(v);if(!Number.isFinite(v))return null;if(v>=-1&&v<=1)return v;if(v>=0&&v<=100)return(v-50)/50;if(v>=-100&&v<=100)return v/100;return clamp(v); }
const ISSUE_MAP=Object.freeze({taxes:['fiscal',1],tax:['fiscal',1],spending:['fiscal',1],regulation:['economics',1],business:['economics',1],welfare:['welfare',1],redistribution:['welfare',1],abortion:['social',1],lgbt:['social',1],civilrights:['social',-1],immigration:['immigration',1],environment:['environment',1],climate:['environment',1],guns:['guns',1],guncontrol:['guns',-1],healthcare:['healthcare',1],health:['healthcare',1],education:['education',1],schoolchoice:['education',1],institutions:['institutional',1],reform:['institutional',-1],party:['partisan',1]});
function boolRule(dimension,direction,weight=1){return{dimension,direction,weight,type:'bool'};}function enumRule(dimension,values,weight=1){return{dimension,values,weight,type:'enum'};}
const POLICY_RULES=Object.freeze({
minwage:[boolRule('economics',-1),boolRule('welfare',-1,.5)],govaid:[boolRule('welfare',-1),boolRule('economics',-1,.4)],basicincome:[boolRule('welfare',-1),boolRule('economics',-1,.5)],lowmain:[enumRule('fiscal',{increase:-1,decrease:1,maintain:0},.5)],midmain:[enumRule('fiscal',{increase:-1,decrease:1,maintain:0},.7)],uppermain:[enumRule('fiscal',{increase:-1,decrease:1,maintain:0},1)],ecogrowth:[enumRule('economics',{spend:-1,cut:1}),enumRule('fiscal',{spend:-1,cut:1})],flattax:[boolRule('fiscal',1)],wealthtax:[boolRule('fiscal',-1),boolRule('welfare',-1,.4)],carbontax:[boolRule('environment',-1),boolRule('fiscal',-.4,.4)],
guncheck:[boolRule('guns',-1)],guncontrol:[boolRule('guns',-1)],banhighcap:[boolRule('guns',-1)],assaultweaponban:[boolRule('guns',-1)],handgunban:[boolRule('guns',-1)],mentalgun:[boolRule('guns',-1,.6)],gundata:[boolRule('guns',-1,.7)],deadlyforce:[boolRule('guns',1)],concealcarry:[boolRule('guns',1)],teacherguns:[boolRule('guns',1)],decgunwait:[boolRule('guns',1)],ccnopermit:[boolRule('guns',1)],ccnowpermit:[boolRule('guns',1)],
commcoll:[boolRule('education',-1)],preschool:[boolRule('education',-1)],teachpay:[boolRule('education',-1)],freetuition:[boolRule('education',-1)],schoolchoice:[boolRule('education',1)],citpath:[boolRule('immigration',-1)],childimm:[boolRule('immigration',-1)],expandvisas:[boolRule('immigration',-1)],tightborder:[boolRule('immigration',1)],denycitizen:[boolRule('immigration',1)],
gaymarriage:[boolRule('social',-1)],marbenefit:[boolRule('social',-1)],recuse:[boolRule('social',-1,.7)],prochoice:[boolRule('social',-1)],transmilserv:[boolRule('social',-1)],illegalabortion:[boolRule('social',1)],pregclinic:[boolRule('social',1,.7)],deathpenalty:[boolRule('social',-1,.5)],laborunion:[boolRule('welfare',-1),boolRule('economics',-1,.5)],incgap:[boolRule('welfare',-1)],cutstamps:[boolRule('welfare',1)],socsecvalue:[boolRule('welfare',-1,.7)],
envgrowth:[enumRule('environment',{env:-1,growth:1})],globalwhuman:[enumRule('environment',{human:-1,nature:.45,doesnotexist:1})],limitpow:[boolRule('environment',-1)],climatepol:[boolRule('environment',-1)],conem:[boolRule('environment',-1)],solwind:[boolRule('environment',-1)],altfuel:[boolRule('environment',-1)],autostand:[boolRule('environment',-1)],reduceem:[boolRule('environment',-1)],greennewdeal:[boolRule('environment',-1)],redfossilfuel:[boolRule('environment',-1)],oilland:[boolRule('environment',1)],moresolar:[enumRule('environment',{more:-1,less:1,same:0},.6)],morewind:[enumRule('environment',{more:-1,less:1,same:0},.6)],moregas:[enumRule('environment',{more:.4,less:-.4,same:0},.4)],moreoil:[enumRule('environment',{more:1,less:-1,same:0},.7)],morenuclear:[enumRule('environment',{more:.15,less:-.15,same:0},.2)],morecoal:[enumRule('environment',{more:1,less:-1,same:0},.7)],
unihealth:[boolRule('healthcare',-1)],expandmedicaid:[boolRule('healthcare',-1)],singlepay:[boolRule('healthcare',-1)],publicoption:[boolRule('healthcare',-1)],regdrugprice:[boolRule('healthcare',-1)],buymedicare:[boolRule('healthcare',-1)],denypreexist:[boolRule('healthcare',-1)],denypregcov:[boolRule('healthcare',-1)],sickpremium:[boolRule('healthcare',-1)],prevservcov:[boolRule('healthcare',-1)],limithealcov:[boolRule('healthcare',-1)],electoralcoll:[boolRule('institutional',-1)],mainmil:[enumRule('fiscal',{increase:.35,decrease:-.35,maintain:0},.25)]});
function blank(){return Object.fromEntries(DIMENSIONS.map(k=>[k,0]));}
function policyValue(rawValue,rule){const value=rawValue&&typeof rawValue==='object'?(rawValue.position??rawValue.value??rawValue.support):rawValue;if(rule.type==='bool'&&typeof value==='boolean')return value?rule.direction:-rule.direction;if(rule.type==='enum'&&value!=null){const key=String(value).toLowerCase().replace(/[^a-z]/g,'');return rule.values[key]??null;}return null;}
function scorePolitician(snapshot={}){const sums=blank(),weights=blank(),evidence=[];function add(dim,value,weight,source,direct=false){const n=direct?(Number.isFinite(value)?clamp(value):null):norm(value,dim);if(n==null)return;sums[dim]+=n*weight;weights[dim]+=weight;evidence.push({dimension:dim,value:n,weight,source});}add('economics',snapshot.fiscalScore,1.5,'fiscalScore');add('fiscal',snapshot.fiscalScore,2,'fiscalScore');add('social',snapshot.socialScore,2,'socialScore');const issues=snapshot.issues&&typeof snapshot.issues==='object'?snapshot.issues:{};for(const[rawKey,rawValue]of Object.entries(issues)){const key=rawKey.toLowerCase().replace(/[^a-z]/g,''),legacy=ISSUE_MAP[key];if(legacy){const value=rawValue&&typeof rawValue==='object'?(rawValue.position??rawValue.value??rawValue.support):rawValue;add(legacy[0],Number(value)*legacy[1],1,`issue:${rawKey}`);if(legacy[0]==='fiscal')add('economics',Number(value)*legacy[1],.6,`issue:${rawKey}`);continue;}const rules=POLICY_RULES[key];if(!rules)continue;for(const rule of rules){const value=policyValue(rawValue,rule);if(value!=null)add(rule.dimension,value,rule.weight,`policy:${rawKey}`,true);}}const dimensions=blank();for(const d of DIMENSIONS)if(weights[d])dimensions[d]=clamp(sums[d]/weights[d]);const observedDims=DIMENSIONS.filter(d=>weights[d]>0).length,evidenceFactor=Math.min(1,evidence.length/12),breadthFactor=observedDims/DIMENSIONS.length,confidence=Math.max(0,Math.min(1,.7*evidenceFactor+.3*breadthFactor));dimensions.intensity=Math.max(dimensions.intensity,Object.entries(dimensions).filter(([k])=>k!=='intensity').reduce((a,[,v])=>a+Math.abs(v),0)/(DIMENSIONS.length-1));return{dimensions,evidence,confidence};}
function distance(a,b,customWeights={}){let total=0,denom=0;for(const d of DIMENSIONS){const w=Number.isFinite(customWeights[d])?Math.max(0,customWeights[d]):1;total+=Math.abs(clamp(a?.[d])-clamp(b?.[d]))*w;denom+=w;}return denom?Math.min(2,total/denom):0;}
module.exports={scorePolitician,distance,norm,clamp,ISSUE_MAP,POLICY_RULES,IDEOLOGY_LABELS};
